### ISSUE TITLE
www.firmenwissen.de

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylistgermany#108]
Site
https://www.firmenwissen.de/az/firmeneintrag/61352/6290154870/ROBERT_WOITHE_RUNDUM_ORGANISATION_BUSINESS_EVENT.html

![2021-01-19 08_19_32-Robert Woithe Rundum Organisation Business   Event, Bad Homburg - Firmenauskunft](https://user-images.githubusercontent.com/4954535/105000909-42772780-5a2f-11eb-9472-ab3fd4e97047.png)
![2021-01-19 08_21_23-Robert Woithe Rundum Organisation Business   Event, Bad Homburg - Firmenauskunft](https://user-images.githubusercontent.com/4954535/105001022-6d617b80-5a2f-11eb-81fb-caa53f963d75.png)

**Comment by monzta** [comment]
Closing as ads from this adblock circumvention are likely to appear again when pushing filters against it.

**Comment by crazyyzarc** [comment]
@monzta does that work for you when you use these filters?
`www.firmenwissen.de##.lNNLNfC`
`www.firmenwissen.de##.YqPiHLGc`

**Comment by crazyyzarc** [comment]
> 
> 
> Closing as ads from this adblock circumvention are likely to appear again when pushing filters against it.

@monzta I've found a two filters, to block these banners:
`www.firmenwissen.de###superbanner`
`www.firmenwissen.de###skyscraper`

**Comment by monzta** [comment]
Added https://github.com/easylist/easylistgermany/commit/3d59122bda5c3781a3fe70992f451fa11e1e825a but they won't last for long
