### ISSUE TITLE
Unblocked ad domain tortuga.services

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#109]
Unblocked ads coming from `embed.tortuga.services`

Example site with the ads: `https://www.travelbook.de/news/eiffelturm-paris-neue-farbe`

<img width="503" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/106899941-3e692c00-66f6-11eb-979d-7dd7221621b3.PNG">

**Comment by Khrin** [comment]
EasyList Germany already contains `||tortuga.services^*/affiliate/$domain=~travelbook.de` (https://github.com/easylist/easylistgermany/blob/master/easylistgermany/easylistgermany_thirdparty.txt#L469) but unfortunately can't be used for this site. I'm sorry for this.
