### ISSUE TITLE
jameda.de

### ISSUE THREAD

**Issue by wout-codes** [easylist/easylistgermany#114]
Ads leftover.
![image](https://user-images.githubusercontent.com/76908410/108871456-25d49d80-7634-11eb-8287-29cef7ffa668.png)

Link: `https://www.jameda.de/arztsuche/?fachgebiet=S53&gruppe=HA&new_search=1&version=5.0.0&where=`

AdGuard for Windows Latest Nightly. AdGuard Base + Tracking Protection Filter + Social Media Filter + AdGuard Annoyances + AdGuard Germany + EasyList Germany.

**Comment by smed79** [comment]
add
* `jameda.de##li[data-testid="top-module"]`

or
* `jameda.de#?#li:-abp-has([data-testid="advertisementSign-flag"])`
