### ISSUE TITLE
werbung.qs-optiker gets blocked but no commercials....

### ISSUE THREAD

**Issue by qsoptiker** [easylist/easylistgermany#12]
Hello,

can someone please fix the issue described in that forum?

thank you

https://forums.lanik.us/viewtopic.php?p=121098#p121098

**Comment by mapx-** [comment]
fixed (by MonztA)
https://github.com/easylist/easylistgermany/commit/6200ca81c5f0ea8ae329196a385c4410877c2320?cn=bWVzc2FnZQ%3D%3D

**Comment by qsoptiker** [comment]
@mapx- thank you!!
