### ISSUE TITLE
chip.de ad image

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#122]
`https://www.chip.de/downloads/CCleaner_16317939.html`

![grafik](https://user-images.githubusercontent.com/48647394/117204973-487ff100-adf1-11eb-8aae-081bc53c864e.png)

possible fix: `static.chip-secured-download.de/*/$image`

**Comment by smed79** [comment]
add 
* `chip.de#$#abort-current-inline-script document.createElement String.fromCharCode`

@wizmak fyi.
