### ISSUE TITLE
www.holidaycheck.de

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylistgermany#126]
Site
https://www.holidaycheck.de/

Filter
`www.holidaycheck.de##.ad-type-branding.hotel-ad`
`www.holidaycheck.de##.ad-type-ranking.hotel-ad`

Before
![2021-06-08 22_39_50-Window](https://user-images.githubusercontent.com/4954535/121254424-82d62580-c8aa-11eb-979b-7485eecf6eb6.png)

After
![2021-06-08 22_42_05-Window](https://user-images.githubusercontent.com/4954535/121254630-c92b8480-c8aa-11eb-8920-b1544d37c616.png)

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/c041c0bc57ff59befd4b76ecdf7ead147b7a1c5b
