### ISSUE TITLE
blitzrechner.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#127]
Ads on `https://www.blitzrechner.de/prozent/`

<img width="612" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/122081357-5157df80-cdff-11eb-8a4b-682f0c5c3ff7.PNG">

filter used: EasyList, EasyPrivacy and EasyList germany

**Comment by smed79** [comment]
add
- `blitzrechner.de##a[rel="nofollow sponsored"]`
or
- `blitzrechner.de#?#.sidebar-box:-abp-contains(Anzeige)`
or
- `||blitzrechner.de/files/images/banner-fashion-de.png`
