### ISSUE TITLE
promobil.de

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylistgermany#132]
When using a list setup closely mimicking those of ABP users, various ads are not blocked on the frontpage. I propose the following entries:
```
||img1.promobil.de/*.gif|$image
promobil.de##img[referrerpolicy=unsafe-url]
promobil.de##div[class*=commercial__container-]
promobil.de##div[class$=topteaser]
```

![image](https://user-images.githubusercontent.com/22780683/124697523-300e7e80-dee7-11eb-9abb-867532be0f3e.png)

Adblockers: uBO 1.36.2b2 + IDCAC 3.3.1
Browser: Chrome 91.0.4472.124 x64
OS: Windows 10 21H1 x64
Lists in use: ↓
![image](https://user-images.githubusercontent.com/22780683/124697778-b0cd7a80-dee7-11eb-8c2b-5816949b4e23.png)

**Comment by Khrin** [comment]
Unfortunately these ads are a little bit tricky to block and your proposed filters would last just a few hours. So, I'm sorry but cannot accept your proposal.

**Comment by smed79** [comment]
@wizmak @arsykan fyi.
