### ISSUE TITLE
Bing Ads

### ISSUE THREAD

**Issue by panvid** [easylist/easylistgermany#139]
Page (example): https://www.bing.com/search?q=dokomi&PC=U316&FORM=CHROMN

URI: https://www.bing.com/aclk?ld= ....

**Comment by panvid** [comment]
Also on News overview as a preview image for other news.

Page (example Thumbnail): https://www.bing.com/search?q=Tennis-Star+Osaka+weint+auf+Pressekonferenz&filters=tnTID%3a%22242369E7-E429-45bb-BAC3-F7B1FE801E76%22+tnVersion%3a%224186361%22+segment%3a%22popularnow.carousel%22+tnCol%3a%225%22+tnOrder%3a%2280f5c00e-7df9-4a27-9ac1-3d3d8a18aa7f%22&FORM=BSPN01

URI: https://www.bing.con/api/v1/mediation/tracking?adUnit=

**Comment by Khrin** [comment]
Hi, what's your browser/adblocker? What lists are you using? (beyond EasyList Germany, of course)

Unfortunately I wasn't able to see any unblocked ads on Bing so far...

**Comment by panvid** [comment]
Oh ok, I use Brave with built-in addblocker and only EasyList Germany as list.

**Comment by ryanbr** [comment]
Screenshot of ads?

**Comment by panvid** [comment]
![image](https://user-images.githubusercontent.com/10072693/130021826-4cd17c3e-8b3f-4f71-a531-b9ab10e7bb39.png)

![image](https://user-images.githubusercontent.com/10072693/130021854-1fd02e89-8eb7-49ac-86df-2af345712772.png)

Here are some of them, may appear not on every opened page.

**Comment by ryanbr** [comment]
Enable Aggressive mode in Brave would fix the Bing ads. (and google ads) @panvid

**Comment by panvid** [comment]
Thanks for the information. Aggressive mode stops showing ads in search results.

The Bing New search (see Screen with horizontal image Gallery) already show the *Anzeige" images (which are advertisment).
