### ISSUE TITLE
IDNA-encode domain names

### ISSUE THREAD

**Issue by mjethani** [easylist/easylistgermany#140]
https://github.com/easylist/easylistgermany/blob/d11219e1f79fc0b2e8ec613a5a4a6246f65fb72a/easylistgermany/easylistgermany_specific_hide.txt#L182

The domain name [should be encoded](https://issues.adblockplus.org/ticket/6647/) as `xn--teilzeithelden-4qb.de`.

**Comment by mjethani** [comment]
You can [lint your filters](https://github.com/mjethani/flint):

```
npm i -g flint-tool
flint easylistgermany_specific_hide.txt
```

**Comment by Khrin** [comment]
Actually it's just a my typo error... Thank you for reporting anyway!
