### ISSUE TITLE
www.uhrzeit.org

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylistgermany#142]
**Site**
https://www.uhrzeit.org/atomuhr.php

**Filter**
`www.uhrzeit.org###anzeige_produkt`
`||www.uhrzeit.org/img/mod/@atomuhr~fullteaser/testsieger.png`

**Before**
![2021-09-08_10-01-13-594_e30IM](https://user-images.githubusercontent.com/4954535/132470873-cbe88a43-6919-4210-94f9-780359dfaa93.png)

**After**
![2021-09-08_10-02-39-711_MQjhC](https://user-images.githubusercontent.com/4954535/132470885-b63d398b-7fe6-4eb7-8bae-e7b82ce377c2.png)

**Comment by Khrin** [comment]
That's not even self-promotion to me, I don't think this should be blocked.
