### ISSUE TITLE
Mein-MMO.de

### ISSUE THREAD

**Issue by panvid** [easylist/easylistgermany#144]
Header and skyscraper on Pageas like https://mein-mmo.de/fifa-22-hypermotion-neue-technik/

I dont know if its blockable, they use own image descriptions and paths :(

**Comment by monzta** [comment]
That's not really blockable without any issues unfortunately. But what I noticed if you reject the cookies of the advertisers, the ads won't show.

**Comment by monzta** [comment]
That's not really blockable without any issues unfortunately. But what I noticed if you reject the cookies of the advertisers, the ads won't show.
