### ISSUE TITLE
t-online.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#147]
Breakage on `https://www.t-online.de/nachrichten/` articles are blocked

![Unbenannt](https://user-images.githubusercontent.com/48647394/135723527-40ff1ee3-6fdd-4446-89ed-a0771ac442ad.PNG)

Browser: Firefox
Adblock: uBlock Origin

`t-online.de##.Tgbox` in EasyList germany breaks the site on my end

**Comment by Khrin** [comment]
Thank you. The filter has been removed.
