### ISSUE TITLE
stadt-bremerhaven.de is blocked

### ISSUE THREAD

**Issue by N1c093** [easylist/easylistgermany#149]
Sadly the website stadt-bremerhaven.de is blocked.

![image](https://user-images.githubusercontent.com/59510296/136015564-4992fa9d-f835-40b5-b85f-46335006b4a3.png)

Do you need additional information?

**Comment by Khrin** [comment]
Hi @N1c093 , the site `stadt-bremerhaven.de` isn't actually completely blocked, only few elements which are considered as advertising are indeed filtered by EasyList Germany. 

Can I ask you what's this tool you've used to check the list, as shown in the pic?

**Comment by N1c093** [comment]
Hi, sadly I can't open the site `stadt-bremerhaven.de` anymore. For me it seems like, that the page is blocked completely:
![image](https://user-images.githubusercontent.com/59510296/136047658-89c54e48-ca9b-4f93-9610-6e915a4339aa.png)
![image](https://user-images.githubusercontent.com/59510296/136048524-89302d00-c0f9-42e2-8352-20a024dd68b5.png)


I used the builtin feature "Query Lists" in Pi-hole:
![image](https://user-images.githubusercontent.com/59510296/136048052-93299fd3-ddc1-411e-931f-f2f4029ee12f.png)

Thank you in advance!

**Comment by Khrin** [comment]
Ok, I understand. Problem here is that EasyList Germany is meant and made for browser extensions like Adblock Plus or Ublock Origin and Pi-hole works differently from the above mentioned extensions. Honestly I don't know how Pi-hole exactly works and if there's something in the settings that may help you in this case, like forcing Pi-hole to separately interpretate certain lists. 

I suggest you to directly get in contact with Pi-hole tech support.
