### ISSUE TITLE
gmx.at [big nasty ad placeholder at the top]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylistgermany#154]
### List the website(s) you're having issues:

`https://www.gmx.at/`

### What happens?

Big nasty ad placeholder at the top.

### List Subscriptions you're using:

- uBO default filter lists
- enabling AdGuard Base does not help either
- enabling DEU: EasyList Germany does not help either
- 
### Your settings

- OS/version: W764SP1
- Browser/version: FF 93 / O 80
- Adblock Extension/version: uBlock Origin 1.38.7b11
### Other details:

![;;](https://user-images.githubusercontent.com/75935068/139658948-0f552463-32a8-40fc-929a-83ce72d1bb6f.png)

**Comment by Khrin** [comment]
I do see some self-promotion banners in this and others placeholders, so these won't be blocked.
