### ISSUE TITLE
tvspielfilm.de + tvtoday.de [big nasty ad placeholders]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylistgermany#157]
### 1
`tvspielfilm.de`: big nasty ad placeholder in the middle

![t](https://user-images.githubusercontent.com/75935068/140503220-8ae7747f-d2e4-422a-9be9-84dff3ef0fc0.png)

### 2
`tvtoday.de`: big nasty ad placeholders: at the top +  in the middle:
![2 (1)](https://user-images.githubusercontent.com/75935068/140504056-f23b9808-b2a7-4ac0-a417-101e8d5a2465.png)
![2 (2)](https://user-images.githubusercontent.com/75935068/140504063-0f9659eb-5a07-4456-9952-4fb57b608048.png)

**Comment by Khrin** [comment]
- `tvspielfilm.de`: https://github.com/easylist/easylistgermany/commit/3d2ded3b4f25bff8ab99b9e9c30723cb3fb839dc
- `tvtoday.de`: https://github.com/easylist/easylistgermany/commit/3d2ded3b4f25bff8ab99b9e9c30723cb3fb839dc

**Comment by felix-22** [comment]
> `tvtoday.de`: [`3d2ded3`](https://github.com/easylist/easylistgermany/commit/3d2ded3b4f25bff8ab99b9e9c30723cb3fb839dc)

Wrong link, you mean this one: https://github.com/easylist/easylistgermany/commit/aa2a423edb4acb326e3c872d6cede96440d54a66.
