### ISSUE TITLE
bild.de [ad placeholders]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylistgermany#158]
It seems the placeholders are of self-promo banners but should it be like this? 
I mean either hide the placeholders or unhide the banners, what's point of leaving such nasty ad placeholders?
Is it because taboola scum must be blocked?

!['](https://user-images.githubusercontent.com/75935068/140505940-93e70202-acd0-4350-a500-e567c126efab.png)

![h](https://user-images.githubusercontent.com/75935068/141149956-782c8e48-b872-448e-8fa2-692de69472a2.png)

**Comment by Khrin** [comment]
@felix-22 What adblocker are you using?

**Comment by felix-22** [comment]
The same like mentioned in the previous issues: https://github.com/easylist/easylistgermany/issues?q=is:issue+is:closed+author:felix-22

**Comment by Khrin** [comment]
What filter lists are you using? Honestly I can't see them with default lists.

**Comment by felix-22** [comment]
Like already mentioned :

 

> felix- 22 : `https://github.com/easylist/easylistgermany/issues/154` :
> 
> ### List Subscriptions you're using:
> 
> 
> - uBO default filter lists
> - enabling AdGuard Base does not help either
> - enabling DEU: EasyList Germany does not help either

I've checked now and still can reproduce on both browsers: Firefox and Opera.

![eeee](https://user-images.githubusercontent.com/75935068/140967265-5e115666-1d30-4fa5-9ed9-e27f5f0ca9b1.png)

**Comment by Khrin** [comment]
If you try to create a custom filter with the element highlighter, what's the result? (If possible create a screenshot for this)

Unfortunately I can't recreate these grey banners, also using your same filters lists.

**Comment by Khrin** [comment]
Added, thank you.
