### ISSUE TITLE
basic-tutorials.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#159]
`https://basic-tutorials.de/news/windows-media-player-bald-auch-fuer-windows-11/`
ad pictures
<details>
<summary> Screenshot </summary>
<img width="1442" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/142768206-fe8614b2-a0dd-40e4-acee-c6d32a5c687b.PNG">

</details>

Adblocker: uBlock Origin 1.38.6
Browser: Firefox developer

**Comment by Khrin** [comment]
I can't see these banners. Please can you post a link of these ads?

**Comment by JobcenterTycoon** [comment]
<details>

<img width="390" alt="Unbenannt2" src="https://user-images.githubusercontent.com/48647394/142912549-2d3fa0b2-5bb3-4525-b9b4-9eb01d2e967e.PNG">
<img width="398" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/142912553-4a7d9735-a833-42f2-93b7-875eb3ea8cd2.PNG">

</details>

Ads appear after accepting cookies
