### ISSUE TITLE
interaktiv.tagesspiegel.de

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylistgermany#162]
Site
https://interaktiv.tagesspiegel.de/lab/bildanalyse-wahlkampf-50-shades-of-power/

Filter
```
interaktiv.tagesspiegel.de##.tslr-ad-tplus-container
```

Before
![2021-11-23_21-31-03-831_4XC2f](https://user-images.githubusercontent.com/4954535/143100043-6e241ec7-acd3-4d62-86be-6e8ba672ba0a.png)
![2021-11-23_21-31-45-629_xqFBU](https://user-images.githubusercontent.com/4954535/143100084-7735601b-652a-466e-9d67-a7a65224c182.png)

**Comment by Khrin** [comment]
This looks like self-promotion and shouldn't by blocked by EasyList Germany, in my opinion.
