### ISSUE TITLE
www.finanzen.net

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylistgermany#163]
Site
https://www.finanzen.net/aktien/volkswagen_vz-aktie

Filter
`www.finanzen.net##.clearfix.newsTeaserWithIcon.newsTeaser`

Before
![2021-11-26_11-07-28-878_gz5SM](https://user-images.githubusercontent.com/4954535/143564009-43ad4753-bdd5-49d1-ac8f-64ca0fd931e9.png)

After
![2021-11-26_11-08-14-924_PH9EV](https://user-images.githubusercontent.com/4954535/143564023-78565855-068e-4df9-8602-4b0d16d63498.png)

**Comment by Khrin** [comment]
This looks like self-promotion to me, I don't think should be blocked.
