### ISSUE TITLE
www.zentrum-der-gesundheit.de

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylistgermany#164]
Site
https://www.zentrum-der-gesundheit.de/rezepte/suppen/cremesuppen/lauchsuppe

Before
![2021-12-05_16-13-34-247_cScDR](https://user-images.githubusercontent.com/4954535/144752360-a95ddbbd-e04c-45c4-8f42-d80942b15408.png)

**Comment by JobcenterTycoon** [comment]
Possible filter: `zentrum-der-gesundheit.de##div[class="noprint"]:-abp-has(span > svg > text)`

**Comment by JobcenterTycoon** [comment]
@Khrin ads are back

**Comment by Khrin** [comment]
> @Khrin ads are back

Fixed (again)

**Comment by JobcenterTycoon** [comment]
Ads are back (again)
