### ISSUE TITLE
filter von stroeermediabrands.de zu generell

### ISSUE THREAD

**Issue by smb-ro** [easylist/easylistgermany#17]
Hi,
durch den Filter 
`||stroeermediabrands.de^$third-party`
ist die Nutzung / Ansicht bestimmter Seiten nicht mehr möglich.
Beispiel ist hier zu finden: http://www.giga.de/games/lf/summoners-war-startseite/

Kann der Eintrag entfernt oder genauer spezifiziert werden, so dass nicht generell alle Subdomains von stroeermediabrands.de blockiert werden?

Danke!

**Comment by monzta** [comment]
Danke für Melden, sollte hiermit behoben sein: https://github.com/easylist/easylistgermany/commit/115607e05f9e3e75cae7d54b0653ff08e50daaf4
