### ISSUE TITLE
n-tv.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#170]
### List the website(s) you're having issues:

`https://www.n-tv.de/`

### What happens?

ads (scroll down to see)
<img width="833" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/148775644-30f9b0e0-3118-4341-97ef-70024a85b734.PNG">

### List Subscriptions you're using:

uBlock Origin with EasyList, EasyPrivacy and EasyList germany

### Your settings

- OS/version: Win 10
- Browser/version: Firefox developer
- Adblock Extension/version: uBlock Origin 1.40.2

**Comment by Khrin** [comment]
In my opinion, these looks like sel-promos and should not be blecked by EasyList Germany.

**Comment by JobcenterTycoon** [comment]
@Khrin could you look again please i get ads in the middle of the page which redirect to the site `https://shop.geuer-geuer-art.de/ntv-art-editions`

<img width="1117" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/162631497-ee108c81-f528-429c-8ffd-a114c5e9a18e.PNG">

**Comment by Khrin** [comment]
@JobcenterTycoon Self-promotion, again.
