### ISSUE TITLE
Wrongfully blocking of websocket

### ISSUE THREAD

**Issue by Sorcy** [easylist/easylistgermany#181]
In easylistgermany_thirdparty.txt you are blocking "ws.beianrufsex.com/boomer/$third-party"

This is not a tracker or something like that. Instead it is a websocket connection for the frontend to quickly be informed of changes in the data of the backend. It is used on different domains because we offer a whitelabel solution for our adult website beianrufsex.com. So it is an integral part of the pages function, and you basically break all of our whitelabels at the moment. Please remove.

**Comment by Khrin** [comment]
Please, can you give an example link from an active site?

**Comment by Sorcy** [comment]
Sure ... 

Here is one of our whitelabels: https://www.telefonsexcam.webcam/ 
Here the websocket is blocked because it is handled as a third party tracker. So the page never updates (and you also wouldn't be able to enter the livecam code from the girls, because the validity check also runs over the websocket).

Here is the original page: https://www.beianrufsex.com/ 
Here the websocket is not blocked and you can see the frequent changes on the page in the online/calling/talking states. Also, here you could enter the livecam code.

**Comment by Khrin** [comment]
Thank you, the filter has been removed.

**Comment by Sorcy** [comment]
Thanks!
