### ISSUE TITLE
elektronikpraxis.vogel.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#191]
`https://www.elektronikpraxis.vogel.de/deutschland-chefin-von-microsoft-metaverse-wird-industrie-erobern-a-9bb60261669a7127e8aacf6140613ebb/`

Ads

<img width="1279" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/171058423-42e412c8-7def-4988-8f6c-98a8acf6bc05.PNG">

Adblocker: uBlock Origin default with EasyList, EasyPrivacy and EasyList germany

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/commit/6fa49cecc054e29fc1270aab74ef44311f6b3064

**Comment by Khrin** [comment]
I don't know what your issue is, but glad you've resolved it for yourself!

**Comment by JobcenterTycoon** [comment]
It was ad reinstertion thats why i fixed in uAssets

**Comment by Khrin** [comment]
Must be another ubo-only issue then.
