### ISSUE TITLE
www.otto.de

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylistgermany#193]
Site: https://www.otto.de/

Filter: `www.otto.de##.karma_brand_promo-list`

Before:
![2022-06-12_13-02-26-608_sGRVO](https://user-images.githubusercontent.com/4954535/173230045-db89b163-be40-4854-9ec4-ed42863bede2.png)
![2022-06-12_13-02-19-385_QW3Ol](https://user-images.githubusercontent.com/4954535/173230046-88a1a3de-5f9d-4956-89e0-e2f47e258d73.png)

**Comment by Khrin** [comment]
This shouldn't be blocked.
