### ISSUE TITLE
eatsmarter.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#199]
### List the website(s) you're having issues:

`https://eatsmarter.de/teilnahmebest%C3%A4tigung`

### What happens?

Ads appear

<details>
<img width="457" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/179538601-52f5f8cc-e0d9-4628-8dc5-813081053150.PNG">
</details>

### List Subscriptions you're using:

uBlock Origin default with EasyList, EasyPrivacy and EasyList Germany

### Your settings

- OS/version: win 10
- Browser/version: firefox developer
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

The ads coming from a iframe from the unblocked adserver `benefits.sovendus.com`. The main site say they are a europe wide network thats why im here

**Comment by Khrin** [comment]
I'm not sure this should be blocked.
