### ISSUE TITLE
fittingcentermonday.com

### ISSUE THREAD

**Issue by xXGamerLionXx** [easylist/easylistgermany#201]
-Website-Daten-
Kategorie: „Malvertising“
Domäne: fittingcentermonday.com
IP-Adressen: 
192.243.59.12
192.243.61.227
Port: 443
Typ: Ausgehend

hoffe ihr könnt damit was anfangen und es gehört auch hier hin dies

bei weiteren fragen dazu immer stellen was ihr noch braucht

**Comment by Khrin** [comment]
@xXGamerLionXx Where you've seen it? On which site was used?

**Comment by xXGamerLionXx** [comment]
whether I can say so freely without making myself liable to prosecution. it was on this site https://aniworld.to/ and the video hoster VOE and I just detected a trojan at Doodstream.com (185.178.208.163).

**Comment by Khrin** [comment]
Added to EasyList.
