### ISSUE TITLE
spiele.bild.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#202]
`https://spiele.bild.de/kreuzwortraetsel/`

The old rule `||partners2.das-onlinespiel.de/client.js?pid=pg_bildnew&_=2.12.3|$script,domain=spiele.bild.de` doesn’t work anymore because the link changed. I get

```
https://partners2.das-onlinespiel.de/client.js?pid=pg_bildnew_kwr&_=2.38.0&locale=de#
https://partners2.das-onlinespiel.de/client.js?pid=pg_bildnew_kwr&zone=crosswords
https://partners2.das-onlinespiel.de/players/videoplayer.js?_=2.12.3
```
now. Also there is a unblocked ad server `servedby.adbility-media.com`

Adblocker: uBlock Origin default with EasyList, EasyPrivacy and EasyList germany

**Comment by JobcenterTycoon** [comment]
@Khrin its too spezific. Your filter works on `https://spiele.bild.de/kreuzwortraetsel/` but not on other games like `https://spiele.bild.de/solitaer/`

Also i see a new ad on the game startpage `https://spiele.bild.de/`

<img width="984" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/186667759-949d063a-34bb-4427-8330-c2d00c620c9b.PNG">

**Comment by JobcenterTycoon** [comment]
Why not just `||partners2.das-onlinespiel.de^$third-party` ?

**Comment by JobcenterTycoon** [comment]
@Khrin filter suggestion for the casio ad

`spiele.bild.de##div[id^="ad-landingpage-"]`

**Comment by Khrin** [comment]
What "Casio ad"? Where it is?

**Comment by JobcenterTycoon** [comment]
The image from https://github.com/easylist/easylistgermany/issues/202#issuecomment-1227208480 is from the top of the page (at the bottom is a second banner)

**Comment by Khrin** [comment]
I can't see any unblocked ads in there, also if using German VPNs.
