### ISSUE TITLE
tracdelight.com

### ISSUE THREAD

**Issue by derToto** [easylist/easylistgermany#21]
The following rule breaks widgets for tracdelight.com. Bloggers and magazines have integrated tracdelight widgets on their websites, and the blocking heavily affects the user's ability to click and purchase the publishers shopping recommendations:

`widgets.tracdelight.com/iframe/$domain=bunte.de|gala.de|stylebook.de`

These kinds of widgets aren't comparable to traditional advertisements. tracdelight widgets often are the content and usually the main focus of a post. Blocking the widgets make the articles and blogposts seem broken and incomplete and therefore make it useless for the reader and drives traffic away from people's websites.

Problem was earlier described here: https://forums.lanik.us/viewtopic.php?f=90&t=34135

**Comment by monzta** [comment]
> tracdelight widgets often are the content and usually the main focus of a post. 

Please provide some example pages for that.

**Comment by derToto** [comment]
Hello monzta,
concerning the three pages, here are some example.

bunte.de:
- „STAR LOOK“ category/section at http://www.bunte.de
- „SHOP THE LOOK“ category/section at http://www.bunte.de/fashion/
e.g. http://www.bunte.de/fashion/looks-fuer-jeden-anlass/shop-look/maxima-der-niederlande-so-wirst-auch-du-stilsicher-wie-die-schoene-koenigin.html

stylebook.de:
- https://www.stylebook.de/fashion/herbst-pullover-trend

gala.de:
- http://www.gala.de/beauty-fashion/fashion/wunschliste--stricktrends-21463348.html

**Comment by monzta** [comment]
Thank you! Removed https://github.com/easylist/easylistgermany/commit/0fa31bc2c43eb18f0b49da3e49dd183f6ae6c81f
