### ISSUE TITLE
gmx.net

### ISSUE THREAD

**Issue by sugarfreesweetener** [easylist/easylistgermany#210]
`https://www.gmx.net/magazine/news/unterrichten-lehramtsabschluss-loesen-quereinsteiger-problem-unterrichtsausfall-37286708` - ads

**Comment by Khrin** [comment]
Probably a little bit more detailed report would've been more helpful, instead of a laconic "ads".

Anyway, there are no unblocked "ads" on this page. Please check if your filter lists are up to date.

**Comment by sugarfreesweetener** [comment]
![image](https://user-images.githubusercontent.com/113248817/191953201-7aa223b8-5c15-4c42-9d89-e1a432988cee.png)

**Comment by Khrin** [comment]
No, these are considered as "self-promotion" and not advertisement, as per EasyList policy.
