### ISSUE TITLE
Wrongfully blocking of VXCASH

### ISSUE THREAD

**Issue by Starlord303** [easylist/easylistgermany#212]
In easylistgermany_thirdparty.txt you are blocking "vxcash.net^$third-party"

This is not a tracker or something like that. Instead this is the official site of our adult  affiliate program vxcash.net. With your block you basically make problems for all our affiliates at the moment. Please remove.

**Comment by Khrin** [comment]
Please can you give any concrete example of where the filter is causing problems? (No demo pages)

**Comment by Starlord303** [comment]
Well this is a bit complicated as the problems happens inside VXCASH and I don't want to force you to make an account ;) ... Affiliates who have activated an ad blocker will no longer see any advertising material.

**Comment by Khrin** [comment]
Quite unlikely the problem is inside `vxcash.net` unless a different domain is used

**Comment by Khrin** [comment]
Removed.
