### ISSUE TITLE
computerbild.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#217]
`https://www.computerbild.de/`

Ads marked with "ANZEIGE" (scroll down to see)

<img width="875" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/197401835-47e76086-9170-45a4-8d4b-155d7ed80c9d.PNG">

Also placeholder (example: `https://www.computerbild.de/artikel/cb-Tipps-Software-Windows-10-11-die-besten-Apps-gratis-laden-12286556.html`)
<img width="317" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/197403091-f65832bf-44c4-4649-9b98-cdfad2850188.PNG">

Adblocker: uBlock Origin

Filter suggestion:

```
computerbild.de##.gridArea__teaserM:-abp-has(span:-abp-contains(Anzeige))
computerbild.de##.superbannerBtfContainer
```

**Comment by Khrin** [comment]
https://github.com/easylist/easylistgermany/commit/fc9c8456994556b724e190408af714d432d173e4
https://github.com/easylist/easylistgermany/commit/a0ab0f73364ea68218337c4bc45d7ec42e9cafce
