### ISSUE TITLE
t-online.de false positive

### ISSUE THREAD

**Issue by BlazDT** [easylist/easylistgermany#22]
easylistgermany/easylistgermany/easylistgermany_specific_hide.txt

![t-online de](https://user-images.githubusercontent.com/34266271/34548317-b2c312c8-f101-11e7-82df-995e8b35bced.png)

t-online.de##img[alt*="Rabatt"]

Screenshot shows correct behaviour, either modify the rule or remove it, thank you.

**Comment by monzta** [comment]
Removed: https://github.com/easylist/easylistgermany/commit/cb5c78246a06af1dd0b5788fb075fa179bcc749a
