### ISSUE TITLE
golem.de - almost all articles invisible

### ISSUE THREAD

**Issue by taleteller** [easylist/easylistgermany#221]
Visiting golem.de almost all articles are white out by cosmetic filter. Disabling easylist DEU makes them visible again.

![Screenshot_20221110_163756](https://user-images.githubusercontent.com/1484333/201139099-62295779-ad45-4fa2-9e78-ca8d7a1531d1.png)

**Comment by Khrin** [comment]
@taleteller What adblocker and what filter lists are you using? (beyond Easylist Germany)

Unfortunately I can't replicate your issue (any specific page is this occurring or just everywhere?)

**Comment by taleteller** [comment]
uBlock Origin 1.45.0 on Firefox 105 for Linux x64. 

I disabled all other lists except "DEU: EasyList Germany" which toggles the issue.

**Comment by monzta** [comment]
@taleteller I made the filter more specific. Can you force an update of your filters and let me know if that fixed the issue?

**Comment by taleteller** [comment]
Yes it fixed the problem for me.

**Comment by monzta** [comment]
Great, thanks for confirming!
