### ISSUE TITLE
Still some ads left

### ISSUE THREAD

**Issue by oliuo1** [easylist/easylistgermany#234]
www.onvista.de

-> white spaces on several pages (nearly all), then also on mobil -> bad surfing experience

example:
https://www.onvista.de/aktien/Zalando-Aktie-DE000ZAL1111   or on homepage https://www.onvista.de or on https://www.onvista.de/news/2023/01-10-roundup-aktien-frankfurt-eroeffnung-dax-nach-starkem-jahresstart-leicht-im-minus-10-26084366

![image](https://user-images.githubusercontent.com/122091080/211551775-1ad5abe4-143a-43b6-b4c1-34aefafedd77.png)

same page, 15 cm below:
![image](https://user-images.githubusercontent.com/122091080/211551874-690f2132-b0e9-4e5b-ad71-941ab7c2f8f1.png)

the before page ending again:
![image](https://user-images.githubusercontent.com/122091080/211552110-9b8b4e24-9bf0-495d-97ef-fc4a84713c86.png)

=========================
www.ariva.de

Ads in Navigation
www.ariva.de and ervery other page:   -> on mouse over "Aktien"
![image](https://user-images.githubusercontent.com/122091080/211554401-82ec91f6-7483-482a-b63d-7f6f45f4c1da.png)

on mouse over "News":
![image](https://user-images.githubusercontent.com/122091080/211554479-f857fc11-c976-4c9f-b452-257e77b0565e.png)

on mouse over "Forum":
![image](https://user-images.githubusercontent.com/122091080/211554527-cc64fcb4-1e00-4477-aef2-a6c86baef1d7.png)

on mouse over "Depot":
![image](https://user-images.githubusercontent.com/122091080/211554607-c47a6eaf-150a-493d-b2a5-6a338cf5672d.png)

Big Ad on many pages example here: https://www.ariva.de/deutsche_boerse-aktie
right side, near footer:
![image](https://user-images.githubusercontent.com/122091080/211555711-47f8d409-872f-431f-9cc4-e08c1aaebb5f.png)

same page 2 backlinks to broker (also on nearly every page) https://www.ariva.de/deutsche_boerse-aktie

![image](https://user-images.githubusercontent.com/122091080/211556109-5afdd7b8-325b-470d-929a-bae015dc8f58.png)

Ad Links to different page: here: https://www.ariva.de/forum/deutsche-boerse-241301?page=42#jump31300745
![image](https://user-images.githubusercontent.com/122091080/211556502-707b96bc-2a7a-41fd-aefa-7664e6f28d04.png)

same ads on the bottom of this (and many other pages)
![image](https://user-images.githubusercontent.com/122091080/211556876-deb55298-be3c-4cf9-9de8-cbaf68ff41dd.png)

========================
www.finanznachrichten.de

https://www.finanznachrichten.de/nachrichten-aktien/sap-se.htm   -> these Text Ads are all over the site

![image](https://user-images.githubusercontent.com/122091080/211559461-a7fac567-e77e-4af6-b4a7-788ea0e26189.png)

https://aktienkurs-orderbuch.finanznachrichten.de/vow3.htm   -> ads on other site (first ad) and down the page again the text ads
![image](https://user-images.githubusercontent.com/122091080/211559812-f37faba1-ac54-481f-a5e5-54a02c137797.png)

thx for your work!

**Comment by Khrin** [comment]
Looks to be all resolved.
