### ISSUE TITLE
ksta.de (ad placeholders)

### ISSUE THREAD

**Issue by garry-ut99** [easylist/easylistgermany#247]
[SCREENSHOOT](https://user-images.githubusercontent.com/72945564/217606999-bf482381-2988-4689-9044-a7fda3336a30.png)

**Comment by garry-ut99** [comment]
here too: `rundschau-online.de`

**Comment by Khrin** [comment]
> here too: `rundschau-online.de`

https://github.com/easylist/easylistgermany/commit/621a87f9632e4f8f2a9dc3a94e268b27b21a025e
