### ISSUE TITLE
netzkino.de

### ISSUE THREAD

**Issue by garry-ut99** [easylist/easylistgermany#248]
Ad placeholders all over the site: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218259199-8814b3fe-0df1-426e-a889-a6d8f329f069.png)

**Comment by garry-ut99** [comment]
This better: `netzkino.de#?#.webSlider > div >:-abp-contains(Die Werbung ist gleich bereit...)`

**Comment by Khrin** [comment]
Probably, but definitely not worthwhile to be added in this case.

**Comment by garry-ut99** [comment]
Curious why "not worthwhile to be added", given the ad placeholders have random classes which might change at any time, and might require to be fixed over and over, unless it's a rare case of a website where random classes won't change for a long time (you are more familiar with the site, so you know it better than me).
