### ISSUE TITLE
[NSFW] Many big ad placeholders in group of porn sites (DE)

### ISSUE THREAD

**Issue by garry-ut99** [easylist/easylistgermany#250]
Same as : https://github.com/easylist/easylist/issues/14954, just for deutche sites:

```
pornofisch.com
pornofelix.com
porndrake.com
pornoente.tv
pornohans.com 
pornohammer.com
pornohelm.com
pornohirsch.net
pornojenny.com
pornoklinge.com
pornoschlange.com
pornotom.com
pornotommy.com
pornozebra.com
pornovideos-hd.com
hdpornos.net
```

**Comment by Khrin** [comment]
Resolved.

**Comment by garry-ut99** [comment]
The commit has fixed some other ad placeholders and things, but not the ones I reported.
Let's say I've realised that the placeholders I reported at the left side can be ignored,
because removing them changes nothing, as videos don't line up all over the page anyway,
but the ad placeholder at the bottom should be hidden because it's annoying and hiding it 
removes this annoyance and save space, example website filter (should be applied for all the websites):
`pornofisch.com###right_content + aside` or
`pornofisch.com#?##right_content + aside:-abp-has(>div>.adsbyexoclick)`

![SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218540495-30c11545-d872-4eeb-b1f9-ee88a01932de.gif)
