### ISSUE TITLE
ableitungsrechner.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#259]
`https://www.ableitungsrechner.net/`

ad

<img width="651" alt="ad" src="https://user-images.githubusercontent.com/48647394/224486956-6cdcba79-8b0f-4a51-ab6d-5181ca0774a0.PNG">

Adblocker: uBlock Origin

**Comment by Khrin** [comment]
Looks to be already blocked.

**Comment by JobcenterTycoon** [comment]
Its unblocked on my end. Clear cookies to see

**Comment by Khrin** [comment]
Unless you see something else different, it's already blocked by `##.ad-slot` in Easylist.

**Comment by JobcenterTycoon** [comment]
There is no `.ad-slot`, see here:

<img width="470" alt="p" src="https://user-images.githubusercontent.com/48647394/224488816-80c30018-0494-4afe-9540-9eb15667904c.PNG">
