### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by barthramsay** [easylist/easylistgermany#269]
`https://www.bild.de`

redirects to an Adblockwall page `https://www.bild.de/adblockwall.html`

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/15139089/230448831-9a5547b7-0d21-4b4f-b730-50356930f20d.png">

Adblocker: uBlock Origin default with EasyList, EasyPrivacy and EasyList germany

**Comment by Khrin** [comment]
Please go ask here: https://github.com/uBlockOrigin/uAssets/issues
