### ISSUE TITLE
tamedia.ch - false positive

### ISSUE THREAD

**Issue by stefanheimes** [easylist/easylistgermany#27]
**Ad Blocker Name:**
Adblock Plus

**Any Lists or Custom Filters:**
exceptionrules.txt
easylistgermany+easylist.txt

**Version, Browser Name:**
Firefox Quantum, Version 58.0 (64-Bit)
Google Chrome, Version 64.0.3282.186 (Offizieller Build) (64-Bit)

**OS Name:**
Winows 10 Pro

_Problem 1: Missing pictures_
Url: ```https://www.tamedia.ch/de/werbung```

Description:
If you take a look at the page, you will see that some pictures are missing on the top of the page after the intro picture. The names of the pictures are:
Advertising_Kombinationen.svg
Advertising_Commercial_Publishing.svg

_Problem 2: Popup_
Url: ```https://www.tamedia.ch/en/brands/details/20-minuten/type/advertising-print```

Description:
If you use the "Seite drucken" button in the upper right corner a popup will be opened. It should display a PDF file but with the active Adblocker, i will see a white popup without any content. If i take a look into the dev-console i see that the pdf was blocked. The path to the file is ```https://www.tamedia.ch/en/brands/details/20-minuten/type/advertising-print/print/1```

Tamedia is an advertising-selling company so we have many words like "Advertising" in any language on the page. Can you help us to fix this.

Thanks.

EasyList Forum Post: ```https://forums.lanik.us/viewtopic.php?f=64&t=40201```

**Comment by monzta** [comment]
Sorry for the delay, should be fixed now.
