### ISSUE TITLE
buzzfeed.de, buzzfeed.at

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#278]
`https://www.buzzfeed.de/buzz/46-deine-mutter-witze-muttertag-humor-lachen-frueher-jugend-liste-90142756.html`
`https://www.buzzfeed.at/`

placeholder

<img width="805" alt="placeholder" src="https://github.com/easylist/easylistgermany/assets/48647394/1954441e-ba5f-427d-829d-e27706432922">

Adblocker: uBlock Origin

Filter suggestion: `buzzfeed.de,buzzfeed.at##div[data-id-advertdfpconf]`

**Comment by monzta** [comment]
There is `##div[data-id-advertdfpconf]` in EasyList, added 3 years ago https://github.com/easylist/easylist/commit/5939d0a 🤔

**Comment by JobcenterTycoon** [comment]
I don’t know why because there is no exception or ghide filter but it need to be specific on my end.

**Comment by JobcenterTycoon** [comment]
Sorry, uBlock Origin was buggy
