### ISSUE TITLE
watson.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#282]
`https://www.watson.de/nachhaltigkeit/klima%20&%20umwelt/130525983-letzte-generation-polizei-droht-mit-heftigem-schritt-aktivisten-unbeeindruckt`

Placeholder

<img width="850" alt="placeholder" src="https://github.com/easylist/easylistgermany/assets/48647394/b5f92f51-a6df-4119-aa39-51cb9b095ab0">

Adblocker: uBlock Origin

**Comment by Khrin** [comment]
It seems to be already correctly blocked with EL+ELG.
