### ISSUE TITLE
bussgeld-info.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#292]
`https://www.bussgeld-info.de/`

placeholder

<img width="633" alt="placeholder1" src="https://github.com/easylist/easylistgermany/assets/48647394/3f16175a-87ca-4982-884c-a33fff601f89">

Adblocker: uBlock Origin

Filter suggestion: `abmahnung.org,arbeitslosenselbsthilfe.org,bussgeld-info.de,koerperverletzung.com##.azk-native-responsive`

**Comment by JobcenterTycoon** [comment]
@Khrin new domain with the same placeholder: `https://www.datenschutz.org/`

**Comment by JobcenterTycoon** [comment]
@Khrin new domain `https://www.urheberrecht.de/`

Filter merged: `abmahnung.org,arbeitslosenselbsthilfe.org,bussgeld-info.de,datenschutz.org,koerperverletzung.com,urheberrecht.de##.azk-native-responsive`

**Comment by JobcenterTycoon** [comment]
@Khrin new domain `https://www.bussgeldkatalog.org/`

Filter merged: `abmahnung.org,arbeitslosenselbsthilfe.org,bussgeld-info.de,bussgeldkatalog.org,datenschutz.org,koerperverletzung.com,urheberrecht.de##.azk-native-responsive`

**Comment by JobcenterTycoon** [comment]
@Khrin new domain `https://www.scheidung.org/tools/`

`abmahnung.org,arbeitslosenselbsthilfe.org,bussgeld-info.de,bussgeldkatalog.net,bussgeldkatalog.org,datenschutz.org,koerperverletzung.com,scheidung.org,urheberrecht.de##.azk-native-responsive`

**Comment by JobcenterTycoon** [comment]
@Khrin new domain `schuldenanalyse-kostenlos.de`

filter merged: `abmahnung.org,arbeitslosenselbsthilfe.org,bussgeld-info.de,bussgeldkatalog.net,bussgeldkatalog.org,datenschutz.org,koerperverletzung.com,scheidung.org,schuldenanalyse-kostenlos.de,urheberrecht.de##.azk-native-responsive`

**Comment by Khrin** [comment]
On which page exactly?

**Comment by JobcenterTycoon** [comment]
`https://www.schuldenanalyse-kostenlos.de/c/pfaendung/`
