### ISSUE TITLE
use of #?# selector in sevecal cases without need for it

### ISSUE THREAD

**Issue by wmyrda** [easylist/easylistgermany#31]
The rules below do not need the use of `#?#` selector as they are not followed by any adblock specific pattern containing `:-abp-*`.

```
spielaffe.de#?##advertising_billboard
spielaffe.de#?##app_advertising_skyscraper_right
chip.de#?#a[data-widget-outbrain-redirect^="http://paid.outbrain.com/network/redir?"]
erdbeerlounge.de#?#a[href^="http://sp.erdbeerlounge.de/"]
kino.de#?#.banner
kino.de#?#.medium-rectangle
```
This causes [problems with adblock2privoxy](https://github.com/essandess/adblock2privoxy/issues/14) converter which at the moment is not able to translate Adblock specific rules. Hence those rules would easily work with regular use of element hiding syntax changing those lines into `##` would be appreciated.

**Comment by monzta** [comment]
Removed them: https://github.com/easylist/easylistgermany/commit/6f2cbf89fa7d268039f2fb9c154e68c1021884b7
