### ISSUE TITLE
gutefrage.net has ads

### ISSUE THREAD

**Issue by Nachtfrische** [easylist/easylistgermany#32]
Hello, 

I can't seem to block the ads that started appearing on gutefrage.net
An example URL would be:
https://www.gutefrage.net/frage/gibt-es-eine-planetenkonstellation-wo-alle-planeten-in-unserem-sonnensystem-hintereinander-stehen

A screenshot of the site looks like this:
https://i.imgur.com/oPBnAOD.png

**Comment by smed79** [comment]
Hello,
no ads for me !!

Please, test this filter
```
@@||gutefrage.net/media/user/*/ad_pics/$image,~third-party
```

**Comment by Nachtfrische** [comment]
Hello,

thank you very much, this filter works perfectly for me!
