### ISSUE TITLE
www.handelsblatt.com

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylistgermany#322]
Site: https://www.handelsblatt.com/29439906.html
Filter: `www.handelsblatt.com##app-commercial-teaser-group`

![2023-10-19_08-48-24-013_KJHqB](https://github.com/easylist/easylistgermany/assets/4954535/c3e53667-f698-40d4-99f8-7075b98500c8)

**Comment by Khrin** [comment]
I don't think this should be blocked, it doesn't seem to contain any adverts.
