### ISSUE TITLE
mein-schoener-garten.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#357]
`https://www.mein-schoener-garten.de/news/winterschneeball-wann-und-wie-schneiden-77962`

Many placeholder around the page

Adblocker: uBlock Origin

**Comment by Chathund** [comment]
@Khrin There are new ad placeholders visible on the home page and on article pages.

Suggestion:

    www.mein-schoener-garten.de##.stf-scroll-container

**Comment by Khrin** [comment]
@Chathund https://github.com/easylist/easylistgermany/commit/641445bda4207ac17031ef6991b6e9ce88516c22
