### ISSUE TITLE
mediaevent.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#361]
`https://www.mediaevent.de/bilddatenformate-jpg-avif-png-webp/`

Placeholder at the right side

<img width="407" alt="tiuoehiumtovgiumogvsduh" src="https://github.com/easylist/easylistgermany/assets/48647394/2fc89762-3cc0-4bee-94e6-9d164ca98f74">

Adblocker: uBlock Origin

A filter can be:

```
mediaevent.de##.topadds
mediaevent.de##.bottomadds
```

**Comment by Khrin** [comment]
I don't see what is going to be gained by adding these filters.
