### ISSUE TITLE
utopia.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#363]
`https://utopia.de/`

placeholder

<img width="423" alt="shshshshshshshztik56utzjztjt" src="https://github.com/easylist/easylistgermany/assets/48647394/bdff5b6d-44eb-427a-9bb0-3cbdddf8aea3">

Adblocker: uBlock Origin

Filter suggestion: `utopia.de###native_ads2`

**Comment by Khrin** [comment]
Appears to no longer exist or is already blocked.

**Comment by JobcenterTycoon** [comment]
Its on the start page after the cookie banner accept, german IP.

**Comment by JobcenterTycoon** [comment]
I discovered a third party ad script which loading this `https://utopix.net/utopia_de/js/loader.js`

**Comment by JobcenterTycoon** [comment]
@Khrin what about to replace the old filter with `||utopix.net/utopia_de/js/loader.js`? Its a ad script which loading more ads and trackers.

Also on `https://utopia.de/ratgeber/ostern-fair-nachhaltig-oekologisch_131059/` i see multiply unblocked ad requests

```
sonic.impactify.media/bidder
pbjs.sskzlabs.com/bid
```

**Comment by JobcenterTycoon** [comment]
@monzta
