### ISSUE TITLE
waz.de

### ISSUE THREAD

**Issue by jlntrt** [easylist/easylistgermany#38]
Hey there,
seems that waz.de renews their whole classes that no filter blocks their ads.

Link: https://www.waz.de

thanks a lot

**Comment by smed79** [comment]
Hi, 
test the below filters
```
##.ad--marker-inner
##.ad--stroer
##.ad__superbanner
##.ad--desktop
waz.de#?#.ad
```
or
```
@@||img.waz.de/img/incoming/*/affiliate.linker/$image,~third-party
```
or
```
||www.waz.de^$csp=script-src 'self' *
```
Warning: _The last one will break some functionality_

**Comment by smed79** [comment]
@wizmak fyi

**Comment by jlntrt** [comment]
Hey @smed79. Unfortunately none of the filters works to me.
At first site, the page is loaded without any ads. After a second, the ads appears. I guess the ads are loaded async by JS. Seems that they did something sophisticated. :thinking:

**Comment by jlntrt** [comment]
I'm using uBlock. But anyway. If the rules above works for you, something in my settings seems to be wrong. It's okay then. I'm trying to get it to work later. 

Thanks!

**Comment by smed79** [comment]
for ublock, add
```
waz.de##+js(abort-on-property-read.js, uabpd3)
```
@okiehsch fyi

**Comment by jlntrt** [comment]
I found out, that the complete ads on this site are blocked just by disabling cosmetic filters.
