### ISSUE TITLE
lustagenten.de / inethoster.org

### ISSUE THREAD

**Issue by vapor-vibez** [easylist/easylistgermany#385]
Hello,

first, I apologize if posting to both the forums and this Github repo at the same time is unwelcome.
Since this is important to our business, I thought I'd try to reiterate my question in hopes of getting some feedback.

---
I work for the company that hosts [Lustagenten](https://lustagenten.de) and administers the domain this issue is about: 

> inethoster.org

inethoster.org appears on EasyList Germany (which I subscribe to via uBlock Origin in Firefox).

Lustagenten's front page features a section which shows who's currently online on the site:
[Image](https://imgur.com/a/7N2sV09)

As you can see in the image above, there are some entries of that section that are just plain black blocks. Those black blocks are supposed to show profile pictures instead which we serve via aforementioned inethoster.org.

Sadly, I cannot guarantee that we never served advertisements or tracking through that domain, but that certainly shouldn't be the case now.

If someone could please tell me how we ended up on EasyList Germany, I'd like to work through this and clear our domain's reputation. Any help at all would be greatly appreciated

**Comment by Khrin** [comment]
@vapor-vibez I've deleted the filter.

**Comment by vapor-vibez** [comment]
@Khrin Thank you very much.

Is there any way to tell how that domain ended up on the list? I'd like to triple-check on our end and make sure that it doesn't happen again.

**Comment by Khrin** [comment]
The filter was added long ago, and the original site to which this refers is probably long gone.
