### ISSUE TITLE
Blocking of Wordpress Plugn

### ISSUE THREAD

**Issue by Sorcy** [easylist/easylistgermany#394]
In [easylistgermany_general_block.txt](https://github.com/easylist/easylistgermany/blob/8aa46759a2809b27cff1a74911b817445303e232/easylistgermany/easylistgermany_general_block.txt#L133) a block for /wp-content/plugins/vxcash/* was added. This completely blocks one of our Wordpress Plugins that people use to display our content on their own wordpress pages.

**Comment by Khrin** [comment]
@Sorcy Any examples sites of where this issue would occur? (no demo pages)

**Comment by Sorcy** [comment]
@Khrin Sure thing. Have a look here: https://www.erotikxxl.de/
Blocking the Plugin breaks the Area beneath "Hot Telefonsex mit kostenloser Cam - Ruf an !" - nothing is displayed.

**Comment by Khrin** [comment]
@Sorcy OK, removed.

**Comment by Sorcy** [comment]
Thanks.
