### ISSUE TITLE
tagesanzeiger.ch

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#405]
`https://www.tagesanzeiger.ch/bund-bricht-ausschreibung-fuer-neue-reservekraftwerke-ab-463265912403`

Placeholder at the top

<img width="1163" alt="plpowakoaijgoiwajgoiwajgoiwaegaggagewsgrdh" src="https://github.com/easylist/easylistgermany/assets/48647394/74ef971c-fac5-4427-b06e-b9eb2bed655a">

Adblocker: uBlock Origin

**Comment by Khrin** [comment]
@JobcenterTycoon It looks like it is already blocked. Can you check?
