### ISSUE TITLE
kaufland.de

### ISSUE THREAD

**Issue by devinlinsley** [easylist/easylistgermany#406]
Currently block list is blocking all product grid items on the homepage of kaufland.de. The rule blocks `.exp-vision`, but in order to only block the ad tiles the rule should be for `.exp-vision__ext-wrapper--spad`.

**Comment by devinlinsley** [comment]
Hi @Khrin, thanks for making the adjustment but the rule change still results in the `.exp-vision` element being blocked. The rule should only block `.exp-vision__ext-wrapper--spad` elements.

The rule should be:
`kaufland.de##.exp-vision__ext-wrapper--spad` not `kaufland.de##.exp-vision:has(.exp-vision__ext-wrapper--spad)`

Thanks in advance!

**Comment by monzta** [comment]
@devinlinsley can you point out where `kaufland.de##.exp-vision:has(.exp-vision__ext-wrapper--spad)` causes issues? I cannot reproduce your issue with updated lists.

**Comment by devinlinsley** [comment]
Hi, thanks for the quick reply. This grid does not render at all with the current rule.

![Screenshot 2024-06-26 at 12 50 43](https://github.com/easylist/easylistgermany/assets/133233976/b438b566-1706-4832-8353-6c3d4df73e43)

**Comment by monzta** [comment]
Thanks! https://github.com/easylist/easylistgermany/commit/bdac0a307f524fd8b0f213a924b3968d77929cd1
