### ISSUE TITLE
Ads appear on n-tv.de

### ISSUE THREAD

**Issue by avanikaein** [easylist/easylistgermany#408]
Using ABP 4.4 
filter lists: EasyList Germany+EasyList & ABP Filters
image ads appear with randomized classnames

<img width="1552" alt="Screenshot 2024-07-16 at 2 40 42 PM" src="https://github.com/user-attachments/assets/2acb65cf-e18e-4def-be21-977a190d2d08">

**Comment by JobcenterTycoon** [comment]
@Khrin they removed `referrerpolicy="unsafe-url"`
