### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by manuallypure** [easylist/easylistgermany#436]
is there a way to permanently remove these two objects?

1.
the BLACK DEALS banner (the ads on this banner keep rotating so now its some lottery but will change again and again)? There is always this kind of Banner with different commercials on it and it even says "Anzeige" (advertisement) but it never gets blocked.

2.
the HEY_ graphic

3.
BILD Marktplatz + BILD Deals

![3910](https://github.com/user-attachments/assets/cd060b66-f7c5-4a66-8e95-733cfcdf3375)
![391056](https://github.com/user-attachments/assets/6dea24e8-c41b-4b0e-989c-b4b897d35099)
<img width="1047" alt="g" src="https://github.com/user-attachments/assets/8476b935-7f8e-442b-bbeb-9584dc08e6b5">
<img width="1053" alt="z" src="https://github.com/user-attachments/assets/d4895fc7-4f7d-40ff-871b-7d98aa7e7eae">

**Comment by Khrin** [comment]
> is there a way to permanently remove these two objects?

Not in EasyList Germany.

**Comment by manuallypure** [comment]
but where else? do you know a filter that i can use in my own filters?

**Comment by Khrin** [comment]
> but where else? do you know a filter that i can use in my own filters?

I don't know. I can't help you, sorry.
