### ISSUE TITLE
einfachkochen.de

### ISSUE THREAD

**Issue by DrDustwolf** [easylist/easylistgermany#440]
#### List the website(s) you're having issues with:

**https://www.einfachkochen.de/rezepte/entenbraten-das-beste-rezept**

#### Screenshot(s) 

![Screenshot_20241211-070904_Iceraven](https://github.com/user-attachments/assets/3722b683-fa41-4532-8a97-bba78a3d6676)

#### Your settings:

- OS/version: Lineage OS 21-20241203-microG-axolotl (Based on Android 14)
- Browser/version: iceraven-2.26.0 (Build #2016058426)
- Ad block extension/version: uBlock Origin: 1.61.2
Firefox Mobile: 133
filterset (summary):
 network: 319682
 cosmetic: 336997
 scriptlet: 57811
 html: 2525
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 6h.2m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103387-18308, 4d.19h.19m
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 89-0, 1d.12h.47m
  https://winhelp2002.mvps.org/hosts.txt: 8729-0, 3d.19h.15m
  adguard-generic: 85609-4259, 3d.19h.15m
  adguard-spyware-url: 1816-131, 3d.19h.15m
  block-lan: 64-0, 14d.12h.9m
  curben-phishing: 544-1, 6h.2m
  adguard-social: 23220-793, 3d.19h.15m
  fanboy-thirdparty_social: 68-19, 4d.19h.19m
  fanboy-cookiemonster: 52251-52246, 3d.4h.50m
  fanboy-social: 16491-16466, 1d.12h.47m
  [22 lists not shown]: [too many]
 default:
  user-filters: 285-5, never
  ublock-filters: 41727-155, 2h.14m Δ
  ublock-badware: 12335-2, 2h.14m Δ
  ublock-privacy: 1621-112, 2h.14m Δ
  ublock-unbreak: 2602-5, 2h.14m Δ
  ublock-quick-fixes: 226-6, 2h.14m Δ
  adguard-mobile: 9979-168, 3d.19h.15m
  easylist: 78072-2425, 2h.14m Δ
  easyprivacy: 53301-558, 2h.14m Δ
  urlhaus-1: 23485-0, 6h.2m
  plowe-0: 3537-1575, 8d.15h.1m
  DEU-0: 7823-62, 6h.2m
filterset (user): [array of 285 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 1825 redacted]
hostRuleset:
 added: [array of 172 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3499 ms (selfie)
 maxAssetCacheWait: 448 ms
 cacheBackend: indexedDB

**Comment by Khrin** [comment]
This is not an advertisement and will not be blocked in EasyList Germany.

**Comment by DrDustwolf** [comment]
Surely is this an advertisement! 🙄

**Comment by Khrin** [comment]
Quite difficult to be sure in most cases, not all Amazon referral links are ads, and in this case it does not appear to be one.

Other ads are regularly blocked.
