### ISSUE TITLE
Spox.com: comment section blocked

### ISSUE THREAD

**Issue by VascoDuckGama** [easylist/easylistgermany#444]
Hello,

there is an issue with the German sport page spox.com: the comment section is placed in several ads and therefore gets filtered.

I reported the issue at the uBlock Origins GitHub as well (https://github.com/uBlockOrigin/uAssets/issues/26468) but they told me to report the issue here.

It seems like the following placeholders need to be checked/adapted?

spox.com##.fco-ad-wrapper
spox.com##.fco-openweb-ad

Can you do that and fix the issue?

Thanks a lot!

**Comment by Khrin** [comment]
I'm sorry, but I couldn't reproduce your issue. It's not caused by EasyList Germany.
