### ISSUE TITLE
tvtv.de

### ISSUE THREAD

**Issue by reloxx13** [easylist/easylistgermany#48]
Heya,

tvtv.de is showing ads

https://www.tvtv.de/programm

i added this rules to hide them on the programm list:

```
#top ad
www.tvtv.de###content > div:nth-of-type(1):not(.program)
www.tvtv.de###content > div:nth-of-type(2):not(.program):has-text(Ad)

#bottom ad
www.tvtv.de###content > div:nth-of-type(4):not(.program)
www.tvtv.de###content > div:nth-of-type(5):not(.program):has-text(Ad)

#right side ad
www.tvtv.de###wrapperListing > div:nth-of-type(1)
```

**Comment by monzta** [comment]
Looks like they are no loger working. Do they work for you?

**Comment by reloxx13** [comment]
heya, yes, no ads here on the programlist

![grafik](https://user-images.githubusercontent.com/14855001/61901603-6633dd00-af20-11e9-846c-ef9f1e07017b.png)

**Comment by reloxx13** [comment]
but it blocks the startpage now :S

**Comment by reloxx13** [comment]
fixed startpage with `:not(#wrapperHome)`

this ar emy filters now:
```
! 6.7.2019 https://www.tvtv.de
www.tvtv.de###content > div:nth-of-type(1):not(.program):not(#wrapperHome)
www.tvtv.de###content > div:nth-of-type(2):not(.program):has-text(Ad)
www.tvtv.de###content > div:nth-of-type(4):not(.program)
www.tvtv.de###content > div:nth-of-type(5):not(.program):has-text(Ad)
www.tvtv.de###wrapperListing > div:nth-of-type(1)
```

**Comment by reloxx13** [comment]
would be better to remove the div before the :has-text(Ad)
but i could not do it myself.

**Comment by monzta** [comment]
Closing as ads from this adblock circumvention are likely to appear again when pushing filters against it.
