### ISSUE TITLE
mein-deal.com

### ISSUE THREAD

**Issue by TimE90** [easylist/easylistgermany#6]
Hallo zusammen,

wir betreuen die Webseite mein-deal.com und entwickeln deren Apps. Wir erhalten vermehrt Berichte von Nutzern des „eBlockers“, dass die iOS- & Android-Apps im heimischen Netzwerk nicht mehr funktionieren. Nach Kontakt mit dem Hersteller eBlocker, liegt es an folgenden Einträgen in der easylistgermany:

||mein-deal.com^$script,third-party
||mein-deal.com^*.jpg$third-party

Wie auch immer die Einträge dort hingekommen sind, sie gehören dort nicht rein. Mein-Deal schaltet nirgendwo Werbung oder ist in irgendeiner Art und Weise ein Tracker.

Kann das bitte jemand überprüfen und berichtigen?

Vielen Dank im Voraus!

**Comment by monzta** [comment]
Es gab mal Werbung, scheinbar aber nun nicht mehr. Hab die Filter nun rausgeschmissen: https://github.com/easylist/easylistgermany/commit/6a9b6058858be0eca65f131921f7a8fea2efaa74
