### ISSUE TITLE
Please add this for removing Ad articles from saechsische.de

### ISSUE THREAD

**Issue by cgommel** [easylist/easylistgermany#62]
Please add this entry:
saechsische.de##.article-box:has(span:has-text(/^Anzeige$/i))

**Comment by cgommel** [comment]
This is how such an ad looks like:
![image](https://user-images.githubusercontent.com/148056/75074421-f4466500-54fb-11ea-863c-86e7f7369a88.png)

**Comment by smed79** [comment]
for Adblock Plus

`saechsische.de#?#article:-abp-has(.landingpage:-abp-has(span:-abp-contains(Anzeige)))`
