### ISSUE TITLE
merkur.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistgermany#67]
`https://www.merkur.de/`

ad picture

<img width="797" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/78769601-db9bec80-798d-11ea-9906-990e0158d77d.PNG">

**Comment by monzta** [comment]
https://github.com/easylist/easylistgermany/commit/1b57e42d512b5e7085ffd0fb1cfdf40e89c79116

**Comment by JobcenterTycoon** [comment]
Merkur ads are back 
<img width="801" alt="pic475" src="https://user-images.githubusercontent.com/48647394/79176087-a8c77d80-7dff-11ea-9f86-4e45be3c5178.PNG">

**Comment by smed79** [comment]
https://github.com/easylist/easylistgermany/commit/991f970c3b55348b36fd51b902c6ce708c2d0b9f#diff-f08fa23c00b7fb05368a7e87654911de
