### ISSUE TITLE
Several Ads 

### ISSUE THREAD

**Issue by emiliou4756** [easylist/easylistgermany#70]
Hello,
all details (screenshots with marked ads) here:

https://github.com/uBlockOrigin/uAssets/issues/7270

**Comment by monzta** [comment]
https://github.com/easylist/easylistgermany/commit/a37e16c6cffa2428bf1f8c271a167e30200ad1f8 
https://github.com/easylist/easylist/commit/03042e6172fb5466aa4a537ac73eae84467f1f39 
https://github.com/easylist/easylist/commit/e146cf33959684e6a8da2d51ce48aa313fafb35b 
https://github.com/easylist/easylist/commit/6999a4d995f6e5f788a24e6c10650f6ca5001761 

Ads on godmode-trader.de seem to appear due to `@@||godmode-trader.de^$ghide` in [uBlock filters](https://github.com/uBlockOrigin/uAssets/blob/f7df38fc465f64be53eb8c5ad73922ba752434c5/filters/filters.txt#L6960). This should either be removed if no longer needed or site-specific lement hiding filters should be added there.

**Comment by kulfoon** [comment]
> [easylist/easylist@03042e6](https://github.com/easylist/easylist/commit/03042e6172fb5466aa4a537ac73eae84467f1f39)
> [easylist/easylist@e146cf3](https://github.com/easylist/easylist/commit/e146cf33959684e6a8da2d51ce48aa313fafb35b)
> [easylist/easylist@6999a4d](https://github.com/easylist/easylist/commit/6999a4d995f6e5f788a24e6c10650f6ca5001761)

May I ask why adding generic network filters for single websites?:
https://publicwww.com/websites/%2Fadspace_finative-/
https://publicwww.com/websites/Ad_SmartBrokerBar/
https://publicwww.com/websites/%2FwsoAdserver./

**Comment by monzta** [comment]
These are generic enough to be added to EasyList.

**Comment by emiliou4756** [comment]
thx.

more here:

https://www.ariva.de/dax-index/news    or https://www.ariva.de/goldpreis-gold-kurs/chart?t=year&boerse_id=136      (footer---ad not always shown)
![image](https://user-images.githubusercontent.com/64039438/79999799-a67ab880-84bc-11ea-8c40-90833b8f8087.png)


https://www.ariva.de/news/dramatische-oelpreis-auswirkungen-deshalb-muessen-infineon-8360384
![image](https://user-images.githubusercontent.com/64039438/80000689-bf379e00-84bd-11ea-95ea-02bb6131cf7b.png)

https://www.finanznachrichten.de/nachrichten-aktien/wirecard-ag.htm

![image](https://user-images.githubusercontent.com/64039438/80001308-82b87200-84be-11ea-8f63-0e9323fa89fe.png)


https://aktienkurs-orderbuch.finanznachrichten.de/wdi.htm
![image](https://user-images.githubusercontent.com/64039438/80001815-1a1dc500-84bf-11ea-8976-808b3bd17587.png)


https://www.finanznachrichten.de/nachrichten-2020-04/49446871-netflix-mit-rekord-coca-cola-mit-umsatzeinbussen-156.htm

![image](https://user-images.githubusercontent.com/64039438/80002727-4ab22e80-84c0-11ea-91e1-0418f2628514.png)

same url, now footer:
![image](https://user-images.githubusercontent.com/64039438/80002796-661d3980-84c0-11ea-8900-b65d5423e2c0.png)

https://www.wallstreet-online.de

![image](https://user-images.githubusercontent.com/64039438/80003016-b2687980-84c0-11ea-86c0-8a97668f0d49.png)

same url, footer:
![image](https://user-images.githubusercontent.com/64039438/80003119-d6c45600-84c0-11ea-9b87-ecf7149a1c56.png)

https://www.wallstreet-online.de/indizes/dax/signale

![image](https://user-images.githubusercontent.com/64039438/80003724-b6e16200-84c1-11ea-82bd-e544b897b04a.png)


https://www.wallstreet-online.de/zertifikat/td99dt-nymex-comex-gold-gold-faktor-12-00x-long-open-end-hsbc

![image](https://user-images.githubusercontent.com/64039438/80004169-4c7cf180-84c2-11ea-8bef-24a580c4e374.png)

https://www.wallstreet-online.de  (mobile view - small window)
![image](https://user-images.githubusercontent.com/64039438/80004302-7209fb00-84c2-11ea-824e-abae1d05027e.png)

https://www.wallstreet-online.de - above footer
![image](https://user-images.githubusercontent.com/64039438/80004518-b72e2d00-84c2-11ea-8fc4-9f7537b21cb8.png)

https://www.wallstreet-online.de/indizes/dax  (mobile view - small window)
![image](https://user-images.githubusercontent.com/64039438/80004590-cdd48400-84c2-11ea-8e75-deba999d8170.png)

https://www.wallstreet-online.de/aktien/teamviewer-aktie

![image](https://user-images.githubusercontent.com/64039438/80005354-bea20600-84c3-11ea-92ef-fdc5af91010d.png)

small view same url:
![image](https://user-images.githubusercontent.com/64039438/80005420-d4afc680-84c3-11ea-8bc9-403fc8767dd2.png)

https://www.boersennews.de

![image](https://user-images.githubusercontent.com/64039438/80006154-cdd58380-84c4-11ea-84dd-fffd1f499012.png)

middle in the homepage:
![image](https://user-images.githubusercontent.com/64039438/80006239-e9408e80-84c4-11ea-9ba6-f948c1c70a0d.png)

https://www.boersennews.de/markt/aktien/detail/de0006231004/

![image](https://user-images.githubusercontent.com/64039438/80006403-1d1bb400-84c5-11ea-929b-2433903d4711.png)

https://www.boersennews.de/nachrichten/artikel/jetzt-wird-es-eng-commerzbank-und-infineon-im-fokus/2215521/

-> also banner above footer
 
![image](https://user-images.githubusercontent.com/64039438/80006470-345aa180-84c5-11ea-87a8-1fd994aaf2a1.png)

https://www.boersennews.de/markt/
![image](https://user-images.githubusercontent.com/64039438/80006679-81d70e80-84c5-11ea-8aba-b2b0286e4dca.png)

https://www.boersennews.de/markt/indizes/detail/de0008469008/

![image](https://user-images.githubusercontent.com/64039438/80007019-fd38c000-84c5-11ea-9682-cdea7093699a.png)


https://www.boersennews.de/community/diskussion/wirecard/448/

![image](https://user-images.githubusercontent.com/64039438/80007086-13df1700-84c6-11ea-958c-56451cd92e7b.png)

**Comment by kulfoon** [comment]
>  monzta : These are generic enough to be added to EasyList.

Which other webpages do the mentioned requests appear on?

**Comment by monzta** [comment]
@emiliou4756 thanks, I'll check this soonish. 

@kulfoon I don't understand..how would I know that?

**Comment by kulfoon** [comment]
> [easylist/easylist@03042e6](https://github.com/easylist/easylist/commit/03042e6172fb5466aa4a537ac73eae84467f1f39)
> [easylist/easylist@e146cf3](https://github.com/easylist/easylist/commit/e146cf33959684e6a8da2d51ce48aa313fafb35b)
> [easylist/easylist@6999a4d](https://github.com/easylist/easylist/commit/6999a4d995f6e5f788a24e6c10650f6ca5001761)

May I ask why adding generic network filters for single websites?:
https://publicwww.com/websites/%2Fadspace_finative-/
https://publicwww.com/websites/Ad_SmartBrokerBar/
https://publicwww.com/websites/%2FwsoAdserver./

**Comment by kulfoon** [comment]
Putting a filter into https://publicwww.com/ will return how many webpages contains it. 
For. ex. https://publicwww.com/websites/%2Fadspace_finative-/ shows that there is only one webpage which contains `/adspace_finative-` , hence `/adspace_finative-$domain=www.ariva.de` would be more logical and efficient than `/adspace_finative-`.

**Comment by monzta** [comment]
If I think a filter is good enough to be generic, I add it to EasyList as it could potentially block/hide something on another page. I doubt publicwww.com crawled every website in the world. So you just don't know if it will work on another site right now or even in the future. I don't understand how `/adspace_finative-$domain=www.ariva.de` is "more logical and efficient" than `/adspace_finative-`. Can you elaborate? The site-specific one will only work on `www.ariva.de`. How is that more more logical and efficient if adding it without the `$domain=` option could potentially block the same or a similar request on another page? I don't see any advantage in using the site-specific one instead.

**Comment by kulfoon** [comment]
> I add it to EasyList as it could potentially block/hide something on another page. 

To not repeat myself, there was already a similiar discussion not long ago wherein I already presented why to be against such too preventive fixing: https://github.com/easylist/easylist/issues/5220#issuecomment-613288321 and Khrin closed this in https://github.com/easylist/easylist/commit/2c2dd7f30532d9da301a8c0cf7b6833f77d8744b accepting my point of view.

> I doubt publicwww.com crawled every website in the world. 

But most of them, and definately all most important ones.

>  So you just don't know if it will work on another site right now or even in the future. 

Nor you, also having just 1 affected website among 1 billion websites indexed by publicwww it's unlikely to find another one, as it shows obvious thing that such a single website with a unique dom/network request's name is just a single alone random case in the ocean.

> I don't see any advantage in using the site-specific one instead.

A performace/resources advantage - when a filter is generic, an adblocker must search every whole webpage a user visit, for a filter occurence, while when a filter is a website specifc, only specifc websites are searched:



<details not-open>
<summary> From uBO:</summary>

> Generic cosmetic filters are those cosmetic filters which are meant to apply on all web sites.
> 
> Though handled efficiently by uBlock₀, generic cosmetic filters may still contribute measurable memory and CPU overhead on some web pages, especially for large and long-lived ones.
> 
> Enabling this option will eliminate the memory and CPU overhead added to web pages as a result of handling generic cosmetic filters, and also lower the memory footprint of uBlock₀ itself.
> 
> It is recommended to enable this option on less powerful devices.

![1](https://user-images.githubusercontent.com/43844449/80094967-75a38d80-8567-11ea-9e77-152404a0425e.gif)

</details>

As seen, it's all about efficiency/performance/resources saving, I haven't counted how many such too-preventive generic filters are present in the list yet so far, but considering the size of both lists EasyList + EasyPrivacy for over 100,000 filters (other lists might be affected as well) there might be hundrends or even thousands of them, and every of such too-preventive filter adds a small overhead to the whole adblocker, so I just wanted to point out to pay attention to not overload the adblockers with such generic filters that cover a single website.

**Comment by monzta** [comment]
> But most of them, and definately all most important ones. 

https://publicwww.com/: `536 229 312 web pages indexed`
https://www.internetlivestats.com/total-number-of-websites/: `1 766 000 000+ Websites online right now`

> Nor you, also having just 1 affected website among 1 billion websites indexed by publicwww it's unlikely to find another one, as it shows obvious thing that such a single website with a unique dom/network request's name is just a single alone random case in the ocean. 

If there is a likelihood, it will usually end up in EasyList as a generic filter. 

> As seen, it's all about efficiency/performance/resources saving

In https://github.com/easylist/easylistgermany/issues/70#issuecomment-617803752 you mention generic blocking rules while in uBO there is a warning for generic element hiding rules. Currently there are 8900 lines in [easylist_general_block.txt](https://github.com/easylist/easylist/blob/8457f9ad420fefcb2a18e0f5463e2e6920d8d56e/easylist/easylist_general_block.txt) and [easylist_general_block_dimensions.txt](https://github.com/easylist/easylist/blob/8457f9ad420fefcb2a18e0f5463e2e6920d8d56e/easylist/easylist_general_block_dimensions.txt). That's without generic adserver ([16188](https://github.com/easylist/easylist/blob/8457f9ad420fefcb2a18e0f5463e2e6920d8d56e/easylist/easylist_adservers.txt)+[1080](https://github.com/easylist/easylist/blob/8457f9ad420fefcb2a18e0f5463e2e6920d8d56e/easylist_adult/adult_adservers.txt)) and third-party ([1854](https://github.com/easylist/easylist/blob/8457f9ad420fefcb2a18e0f5463e2e6920d8d56e/easylist/easylist_thirdparty.txt)+[454](https://github.com/easylist/easylist/blob/8457f9ad420fefcb2a18e0f5463e2e6920d8d56e/easylist_adult/adult_thirdparty.txt)) filters (lines =| filters as there are also some comments). I'm not aware of any perfomance issues with such filters. I know that processing and applying filters in general has been improved considerably in the last years in mayor adblock extesion and products such as Cliqz, Adblock Plus, AdBlock and I think Brave too.

**Comment by monzta** [comment]
@emiliou4756 

> https://www.ariva.de/news/dramatische-oelpreis-auswirkungen-deshalb-muessen-infineon-8360384 

Showing due to `@@||ariva.de^$ghide` in uBlock filters. It should be removed or add `ariva.de##.werb_textlink` to uBlock filters.

**Comment by emiliou4756** [comment]
regarding godmode an ariva: who maintains ublock filters?

here some others: 
https://www.zeit.de/zustimmung?url=https%3A%2F%2Fwww.zeit.de%2Findex
https://www.spiegel.de/consent-a-?targetUrl=https%3A%2F%2Fwww.spiegel.de%2F
https://www.mobiflip.de/shortnews/volkswagen-id3-ionity-preise-kosten-marketing/

**Comment by kulfoon** [comment]
> montza :
> 
> > kulfoon: But most of them, and definately all most important ones.
> 
> https://publicwww.com/: `536 229 312 web pages indexed`
> https://www.internetlivestats.com/total-number-of-websites/: `1 766 000 000+ Websites online right now`

Yes, beg pardon, my overlooking, I just somehow misread total number of web pages indexed on publicwww as 1 000 000 000 / 1 billion.

> 
> > kulfoon: Nor you, also having just 1 affected website among 1 billion websites indexed by publicwww it's unlikely to find another one, as it shows obvious thing that such a single website with a unique dom/network request's name is just a single alone random case in the ocean.
> 
> montza: If there is a likelihood, it will usually end up in EasyList as a generic filter.

Well, then have fun littering filters lists with such weird unefficient generic filters made for 1 single website, with a hope they will fix 1 more website semewhere in the rest of 1 000 000 000 remaining  websites, btw it also doesn't comply (does not have to, of course), with https://github.com/uBlockOrigin/uBlock-issues/issues/738#issuecomment-536180398.

> 
> > kulfoon: As seen, it's all about efficiency/performance/resources saving
> 
> montza: In [#70 (comment)](https://github.com/easylist/easylistgermany/issues/70#issuecomment-617803752) you mention generic blocking rules while in uBO there is a warning for generic element hiding rules. 

Just to be clear, In the quoted comment I mentioned both blocking and hiding rules, not only blocking rules, (see the middle one), and even blocking rules, not much as hiding rules, still eat cycles, because must be processed, and also adding generic filters for 1 known single website is just weird. 

> montza: (...) I'm not aware of any perfomance issues with such filters. I know that processing and applying filters in general has been improved considerably in the last years in mayor adblock extesion and products such as Cliqz, Adblock Plus, AdBlock and I think Brave too.

Yea, but it's not about some critical performacne issue, but rather about an approach, they still eat some cycles, especially given the fact users have other addons installed in their browsers as well, and if each of the addons will unnesecary eat some cycles, we would end having webpages loading slower, I just share and follow gorhill's efficiency based approach, to save cycles where possible.

**Comment by monzta** [comment]
@emiliou4756 ping @mapx- 

Where do you see ads on the other sites?

**Comment by kulfoon** [comment]
>  https://github.com/uBlockOrigin/uBlock-issues/issues/738#issuecomment-619450820

Great, if it just was written in the tooltip I mentioned, that would be good, but it seems you are not of those who claim that their description may have been misleading and making you looking like denying your own tooltip. I didn't dig so deep into uBO's code, as I just sticked to what was suggested in the uBO's tooltip, thus I thought every added generic filter eats some cycles. But as seen, since now I won't trust at 100% to any tooltip anymore in any program.

As for your "All I see is you wanting to argue for the sake of arguing." + locking the thread it reminds me https://github.com/easylist/easylist/issues/4067#issuecomment-535877716, how convenient it is, no further comment on such admins, I won't contribute to any uBO repo anymore.

Also what I wrote about uBock-user and Khirin still holds up, unless they explain their two-faced behaviour.

montza, you are the man, even despite we had a different opinion, thx for talking and being a man  unlike all of these other dogs who locks threads / refuse to reply / are two-faced / are trolling by emojis etc.

**Comment by mapx-** [comment]
@emiliou4756 
fixed anti adb warning for uBO
https://github.com/uBlockOrigin/uAssets/commit/0510542c588542bcb37e0551dba6d051f415b0d4

**Comment by mapx-** [comment]
@monzta 

on `spiegel.de` (home page for example) , even disabling `ghide` filter there are some blank placeholders 
![image](https://user-images.githubusercontent.com/10303732/80308182-be5c8000-87cd-11ea-9c9a-be1516fb5692.png)

**Comment by kulfoon** [comment]
mapx, as I've resigned from contribution to uBO repos, wanted to say thx to you, you are the man too

**Comment by mapx-** [comment]
@monzta for the big placeholder see if helps:
`spiegel.de##[data-component="HTMLEmbed"]`

**Comment by emiliou4756** [comment]
@mapx- 
always in private surfmode - sometimes in normal mode...

Spiegel: 
![image](https://user-images.githubusercontent.com/64039438/80356341-9de9ff80-8879-11ea-9ee4-f545a6446c0b.png)


Zeit:
![image](https://user-images.githubusercontent.com/64039438/80356291-89a60280-8879-11ea-81a4-56f05812554a.png)

**Comment by mapx-** [comment]
@emiliou4756  It's not about ads or anti adblocking.

I tried for example `spiegel.de##+js(aopr, document.cookie)`
but it seems is breaking the comments and possibly other stuff.
