### ISSUE TITLE
Some Ads

### ISSUE THREAD

**Issue by emiliou4756** [easylist/easylistgermany#71]
https://www.t-online.de/unterhaltung/

![image](https://user-images.githubusercontent.com/64039438/80989568-66f58a00-8e35-11ea-92d4-e911ae5a9450.png)

https://www.t-online.de/auto/

![image](https://user-images.githubusercontent.com/64039438/80989785-b3d96080-8e35-11ea-8e98-11b763e234b0.png)

https://www.t-online.de/auto/technik/id_78314894/tiere-im-auto-transportieren-isofix-verankerung-hilft.html

![image](https://user-images.githubusercontent.com/64039438/80989839-c784c700-8e35-11ea-9f46-81af48295caa.png)

https://www.t-online.de/unterhaltung/stars/id_87815004/sabine-zimmermann-68-ex-aktenzeichen-xy-moderatorin-ist-gestorben.html

![image](https://user-images.githubusercontent.com/64039438/80989962-e8e5b300-8e35-11ea-9b7b-1e9a8ed0c033.png)

https://www.chip.de/news/WiFi-6E-fuer-FritzBox-und-Co.-Schneller-WLAN-Standard-wird-massentauglich_157794271.html

![image](https://user-images.githubusercontent.com/64039438/80990368-83de8d00-8e36-11ea-813c-e08f0fa49186.png)

https://www.sport1.de/
footer:
![image](https://user-images.githubusercontent.com/64039438/80991136-dd938700-8e37-11ea-93b4-4bac0f106e7c.png)

https://www.finanzen100.de/aktien/sap-wkn-716460_H1626871619_82849/
![image](https://user-images.githubusercontent.com/64039438/80991524-79bd8e00-8e38-11ea-8616-3fda97c07de8.png)

https://www.finanzen100.de/finanznachrichten/boerse/wirecard-nach-kurssturz-ein-spekulatives-schnaeppchen_H1529365355_11951416/
in each artikle:

![image](https://user-images.githubusercontent.com/64039438/80991779-d5881700-8e38-11ea-876f-ccc0922aa174.png)

**Comment by monzta** [comment]
> https://www.t-online.de/unterhaltung/stars/id_87815004/sabine-zimmermann-68-ex-aktenzeichen-xy-moderatorin-ist-gestorben.html
> 
> ![image](https://user-images.githubusercontent.com/64039438/80989962-e8e5b300-8e35-11ea-9b7b-1e9a8ed0c033.png)

I cannot reproduce the top ad. You are using uBlock Origin?

**Comment by emiliou4756** [comment]
>>I cannot reproduce the top ad. You are using uBlock Origin?
yes but i cant reproduce either. so just drop it ;)

https://www.abendzeitung-muenchen.de/
![image](https://user-images.githubusercontent.com/64039438/80992017-31eb3680-8e39-11ea-999e-2c66d3e7cf6b.png)

**Comment by emiliou4756** [comment]
https://www.boerse-online.de/aktie/volkswagen_vz-aktie
-> not always this adds

![image](https://user-images.githubusercontent.com/64039438/81088631-83f49080-8efb-11ea-99db-15f765db3e32.png)

https://www.boerse-online.de/aktien/realtimekurs/volkswagen_vz
https://www.boerse-online.de/aktien/aktienempfehlungen

![image](https://user-images.githubusercontent.com/64039438/81088716-a5ee1300-8efb-11ea-93ab-ca9c74cc5ed8.png)

https://www.chefkoch.de/rezepte/2341781372709532/Spaghetti-alla-carbonara.html

![image](https://user-images.githubusercontent.com/64039438/81089111-3af10c00-8efc-11ea-8342-eddfc39e3493.png)

https://www.chefkoch.de/magazin/artikel/6497/Chefkoch/backrezepte-zum-muttertag.html

![image](https://user-images.githubusercontent.com/64039438/81089233-62e06f80-8efc-11ea-9ebc-345589660f3f.png)

https://www.boerse.de/
![image](https://user-images.githubusercontent.com/64039438/81089967-56104b80-8efd-11ea-85c3-674705710df8.png)

https://www.finanzen.net/nachricht/aktien/cypress-staerkt-geschaeft-infineon-aktie-dennoch-freundlich-infineon-warnt-wegen-corona-auswirkungen-vor-umsatzrueckgang-8825165

below evry artikle 2 adds - here 2 examples

![image](https://user-images.githubusercontent.com/64039438/81090704-7096f480-8efe-11ea-8ca6-2e2052b4d4b9.png)


https://www.finanzen.net/nachricht/aktien/erste-schaetzungen-infineon-veroeffentlicht-zahlen-zum-vergangenen-quartal-8759739

![image](https://user-images.githubusercontent.com/64039438/81090822-9623fe00-8efe-11ea-969c-0d42ffbe2724.png)


https://www.finanzen.net/

![image](https://user-images.githubusercontent.com/64039438/81091066-f6b33b00-8efe-11ea-940e-430bf24b46ae.png)

![image](https://user-images.githubusercontent.com/64039438/81091128-0d599200-8eff-11ea-8c03-487cdca8d2dc.png)

![image](https://user-images.githubusercontent.com/64039438/81091201-2bbf8d80-8eff-11ea-8bcb-48c709b8e095.png)

https://www.finanzen.net/index/dax-realtime

![image](https://user-images.githubusercontent.com/64039438/81091594-bbfdd280-8eff-11ea-916b-0545b705cc59.png)

![image](https://user-images.githubusercontent.com/64039438/81091689-dd5ebe80-8eff-11ea-8dd6-5a06624b1b56.png)

https://www.finanzen.net/nachricht/aktien/fed-entscheid-voraus-hoffnung-auf-corona-medikament-dax-geht-deutlich-ueber-11-000-punkte-marke-in-den-feierabend-8801193

![image](https://user-images.githubusercontent.com/64039438/81091953-3595c080-8f00-11ea-942d-d982747823db.png)

https://www.finanzen.net/aktien/wirecard-aktie

![image](https://user-images.githubusercontent.com/64039438/81092381-cbc9e680-8f00-11ea-88a2-927968f11bd5.png)

![image](https://user-images.githubusercontent.com/64039438/81092433-e0a67a00-8f00-11ea-8b93-0f65a10ee59f.png)

![image](https://user-images.githubusercontent.com/64039438/81092565-0e8bbe80-8f01-11ea-8276-49e45432db10.png)

![image](https://user-images.githubusercontent.com/64039438/81092925-9f629a00-8f01-11ea-9139-b35b9b0a41a8.png)


Search:
![image](https://user-images.githubusercontent.com/64039438/81092857-86f27f80-8f01-11ea-9fd8-b1b7ceb6c8e0.png)

**Comment by emiliou4756** [comment]
https://www.wallstreet-online.de/
![image](https://user-images.githubusercontent.com/64039438/81093472-7abaf200-8f02-11ea-866d-e9f627e927f8.png)

![image](https://user-images.githubusercontent.com/64039438/81093574-9a521a80-8f02-11ea-9e29-c89e03c999c5.png)

https://www.wallstreet-online.de/aktien/wirecard-aktie

![image](https://user-images.githubusercontent.com/64039438/81093688-ba81d980-8f02-11ea-8a24-4b60bfb8cf41.png)

**Comment by monzta** [comment]
> 
> 
> https://www.boerse-online.de/aktie/volkswagen_vz-aktie
> -> not always this adds
> 
> ![image](https://user-images.githubusercontent.com/64039438/81088631-83f49080-8efb-11ea-99db-15f765db3e32.png)

These ads are not easy to remove and this has to be taken care of in uBlock filters.

> https://www.chefkoch.de/rezepte/2341781372709532/Spaghetti-alla-carbonara.html
> 
> ![image](https://user-images.githubusercontent.com/64039438/81089111-3af10c00-8efc-11ea-8342-eddfc39e3493.png)

Didn't remove these buttons as I think they might be useful for the user.

> https://www.finanzen.net/aktien/wirecard-aktie
> 
> ![image](https://user-images.githubusercontent.com/64039438/81092433-e0a67a00-8f00-11ea-8b93-0f65a10ee59f.png)

Wasn't able to reproduce.

Everything else reported should now be covered.
