### ISSUE TITLE
Textlink

### ISSUE THREAD

**Issue by emiliou4756** [easylist/easylistgermany#72]
https://www.sport1.de/fussball/bundesliga/2020/05/fc-bayern-philippe-coutinho-koennte-bei-saisonfinale-mitwirken-laut-flick

![image](https://user-images.githubusercontent.com/64039438/81582517-708c6e00-93b0-11ea-88be-3b619c0a47be.png)

these are still there- from here further below see pics: https://github.com/easylist/easylistgermany/issues/71#issuecomment-623628557

thanx

**Comment by monzta** [comment]
Fixed in https://github.com/uBlockOrigin/uAssets/commit/223ca5e
