### ISSUE TITLE
Ads bi

### ISSUE THREAD

**Issue by emiliou4756** [easylist/easylistgermany#73]
https://www.businessinsider.de/wirtschaft/handel/inside-zalando-ueberwachung-oder-industriestandard-so-kontrolliert-der-online-haendler-die-mitarbeiter-in-seinen-logistikzentren/

Firefox and ublock 

and:
these tickets a a long time open:

https://github.com/easylist/easylistgermany/issues/72

https://github.com/easylist/easylistgermany/issues/71#issuecomment-623628557

thank you

![image](https://user-images.githubusercontent.com/64039438/81948014-8349b180-9601-11ea-87aa-13d063ca0716.png)

**Comment by llacb47** [comment]
`businessinsider.de` was fixed in uBo, update your lists.
