### ISSUE TITLE
Metadata timestamp

### ISSUE THREAD

**Issue by stonecrusher** [easylist/easylistgermany#74]
Something went wrong here, only the `%timestamp%` variable is visible instead of the date:
```
[Adblock Plus 1.1]
! Version: 202006091012
! Title: EasyList Germany
! EasyList Germany - Deutsche Ergänzung zu EasyList
! Last modified: %timestamp%
```

**Comment by monzta** [comment]
Thanks, should be fixed now with this change: https://github.com/easylist/easylistgermany/commit/5bf5785
