### ISSUE TITLE
mtb-news.de Bilder geblockt

### ISSUE THREAD

**Issue by sp00n** [easylist/easylistgermany#8]
Der Filter /news.de\/.*\.(jpg|gif|jpeg|png|bmp)$/$first-party,image wird fälschlicherweise auch auf mtb-news.de angewendet, und blockt so diverse Bilder (Hintergrundstyles, hochgeladene Bilder, etc).

**Comment by mjaschen** [comment]
Thread regarding this issue in EasyList forums: https://forums.lanik.us/viewtopic.php?f=90&t=36316

**Comment by monzta** [comment]
Sollte nun behoben sein.
