### ISSUE TITLE
az.com.na

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylistgermany#85]
A false-positive-blocked rightside bar, and some placeholders. Example page: `https://www.az.com.na/`. I propose adding the following entries to EasyList Germany:
```
! Placeholders
||nmh.my.na/main/products^$domain=az.com.na
az.com.na#?#aside:-abp-has(img[src*="/adverts/"])

! Caused by EasyList
az.com.na#@#.adverts
az.com.na#@##ad_block_1
! Caused by Liste FR
az.com.na#@#[id^="ad_block_"]
```

![image](https://user-images.githubusercontent.com/22780683/94344818-31d71780-0022-11eb-80aa-1e31484449ec.png)

### My lists at the time of testing

![image](https://user-images.githubusercontent.com/22780683/94344806-1f5cde00-0022-11eb-83e2-f260d2336815.png)

### Environment:

Adblocker: Nano Adblocker 1.0.0.153 + Nano Defender 15.0.0.205 + I Don't Care About Cookies 3.2.1
Browser: Chrome 85.0.4183.121 x64
OS: Windows 10 May 2020 Update

**Comment by monzta** [comment]
@DandelionSprout Thanks! Please report the false positive in Liste FR to its author.
