### ISSUE TITLE
hifi-forum.de

### ISSUE THREAD

**Issue by chidniu** [easylist/easylistgermany#87]
There is currently an unblocked ad banner at the top of hifi-forum.de
![Clipboard01](https://user-images.githubusercontent.com/5339604/94847511-f8881880-0422-11eb-9699-07598bfd6f40.png)

**Comment by crazyyzarc** [comment]
@chidniu With the current state of the filter, it should not pop up.

**Comment by monzta** [comment]
Closing as ads from this adblock circumvention are likely to appear again when pushing filters against it.
