### ISSUE TITLE
comunio.de

### ISSUE THREAD

**Issue by pwalkerz** [easylist/easylistgermany#9]
Comunio ist die bekannteste Fußballmanager community (zumindest in Deutschland) und seit einiger Zeit gibt es dort ein neues layout per default welches nervige riesige Werbebanner enthält, leider werden dort dynamische ids und klassen verwendet für die Webelemente als auch sourcelinks weshalb ich versucht habe das ganze per css selektoren und relativen pfaden zu lösen (getestet auf login seite, Transfermarkt und Aufstellung) 

comunio.de##div[ng-class="getReklameContainerClass()"]
comunio.de##div[class="main_container bg_main_green"]>div>img
comunio.de##div#main-layout>div.home_container.with_home_bg_image>div>div>img
comunio.de##div.main_container>div>img

Für die classic variante classic.comunio.de gibt es schon filtereinträge, welche aber auch nicht mehr funktionieren. Hier meine Lösung:
||classic.comunio.de/i/2/screenshots/*/*/screenshot_*$image,domain=classic.comunio.de

**Comment by monzta** [comment]
see https://github.com/easylist/easylistgermany/pull/10
