### ISSUE TITLE
wochenblatt.cc

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylistgermany#92]
Various ad banners on `https://wochenblatt.cc/buergermeister-auf-der-flucht-einfach-nur-schamlos/`. I propose:
```
||wochenblatt.cc/wp-content/uploads/*.gif^
||wochenblatt.cc/wp-content/uploads/*/Werbung-$image
||wochenblatt.cc/wp-content/uploads/*/elehogkl.jpg^
```

![image](https://user-images.githubusercontent.com/22780683/98815558-9b22b680-2427-11eb-9c95-d4af4489db05.png)

Test environment:
OS: Windows 10 20H2
Tools: uBO 1.30.9b14 + IDCAC 3.2.4
Browser: Chrome 86.0.4240.193 x64
Lists: ↓
![image](https://user-images.githubusercontent.com/22780683/98812693-38c7b700-2423-11eb-81bc-5ca7a9e9044d.png)

**Comment by Khrin** [comment]
https://github.com/easylist/easylistgermany/commit/fffd4d57be0b81cfc6fa4af58ee3c700b9d9e83d
