### ISSUE TITLE
www.appgefahren.de

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylistgermany#99]
Isn't it more efficient to set the filter `##.aawp` for all pages?

Filter:
`www.appgefahren.de##.aawp`

Site:
https://www.appgefahren.de/airpods-max-jetzt-auch-bei-amazon-erhaeltlich-291294.html

Before:
![2020-12-15 06_55_17-AirPods Max jetzt auch bei Amazon erhältlich - appgefahren de](https://user-images.githubusercontent.com/4954535/102176928-b8252c00-3ea2-11eb-97a2-5846f4179793.png)

After:
![2020-12-15 06_55_26-AirPods Max jetzt auch bei Amazon erhältlich - appgefahren de](https://user-images.githubusercontent.com/4954535/102176938-bb201c80-3ea2-11eb-8a1b-222eb030e365.png)

**Comment by Khrin** [comment]
Better to apply this filter site-specific, in my opinion.
